export const LANG = {
    en: {
        title: "Thirunallur Jallikattu",
        subtitle: "The Ultimate Battle of Valor",
        heroBtn: "Book Tokens",
        heroSec: "Live Status",
        about: {
            title: "The Legacy of Thennalur",
            desc: "Experience the adrenaline of one of Thirunallur's oldest traditions. Where bulls are worshipped and valor is tested.",
            date: "Date: Jan 16 (Mattu Pongal)",
            loc: "Location: Thirunallur, Sri Muthu Mari Amman Temple\nDistrict: Pudukottai - 621316"
        },
        countdown: {
            title: "PONGAL",
            subtitle: "Countdown Begins",
            days: "DAYS"
        },
        booking: {
            title: "Official Registration",
            selectType: "Select Registration Type",
            bullOwner: "Bull Registration",
            bullTamer: "Tamer Registration",
            step1: "Personal Details",
            step2: "Specific Details",
            step3: "Documents",
            step4: "Review & Pay",
            next: "Next",
            back: "Back",
            payBtn: "Pay & Register",
            processing: "Processing...",
            success: "Registration Successful!",
            fields: {
                name: "Full Name",
                phone: "Phone Number",
                email: "Email Address",
                aadhar: "Aadhar Number",
                district: "District",
                village: "Revenue Village",
                address: "Full Address",
                bullName: "Bull Name",
                bullAge: "Bull Age",
                breed: "Breed / Variety",
                height: "Height (cm)",
                marks: "Identification Marks",
                tamerAge: "Age",
                weight: "Weight (kg)",
                bloodGroup: "Blood Group",
                photo: "Passport Size Photo",
                aadharCard: "Aadhar Card",
                medicalCert: "Medical Fitness Certificate",
                vaccineCert: "Vaccination Certificate",
                place: "Place",
                bloodShort: "Blood",
                bullShort: "Bull",
                nameShort: "Name",
                breedShort: "Breed",
                weightShort: "Weight",
                aadharBull: "Aadhar with Bull Photo",
                veterinary: "Veterinary Certificate",
                fitness: "Fitness Certificate",
                animalWelfare: "Animal Welfare Certificate",
                doorNo: "Door No / Area / Street",
                taluk: "Taluk",
                pincode: "Pincode",
                assistName: "Assistant's Name",
                assistMobile: "Assistant's Mobile Number",
                bullColor: "Bull's Color",
                bullDentition: "Bull's Dentition",
                bullNative: "Is Bull Native?",
                hornLength: "Bull Horn's length (in cm)",
                icd: "Inter-Cornual Distance (ICD) (in cm)",
                vetName: "Name of Veterinary Dispensary",
                medicalCertNo: "Bull's Medical Certificate No",
                vaccineFMD: "Vaccination Particulars (FMD)",
                ownerAadharFile: "Upload Aadhaar (Only PDF)",
                bullMedicalFile: "Bull's Medical Certificate (Only PDF)",
                bullPhotoFile: "Bull's Picture with Owner & Assistant (Only jpg)",
                native: "Native",
                cross: "Cross",
                yes: "Yes",
                no: "No",
                pledge: "Owner Pledge Form",
                pledgeText: "I hereby pledge that I will participate in the Jallikattu event subject to the Jallikattu rules of the Government and I will not give stimulants or harass my bull.",
                // Tamer Specific
                tamerFormTitle: "Jallikattu Bull Tamer's Registration Form",
                hostingDistrict: "Select Hosting District",
                jallikattuLocation: "Jallikattu Location",
                submittingLocation: "Submitting Location",
                emergencyName: "Emergency Contact Name",
                emergencyMobile: "Emergency Contact Person Mobile Number",
                declarationTitle: "Declaration",
                declarationRule1: "1. Should not have recent injury/surgery/surgical scars",
                declarationRule2: "2. Hypertensive patients on examinations are not allowed",
                declarationRule3: "3. Alcohol intake will be checked on the day of Jallikattu event through analyzer. If found to be under influence of alcohol, the applicant will be debarred"
            }
        }
    },
    ta: {
        title: "திருநல்லூர் ஜல்லிக்கட்டு",
        subtitle: "வீரம் விளையும் மண்",
        heroBtn: "டோக்கன் முன்பதிவு",
        heroSec: "நேரலை",
        about: {
            title: "தென்னலூர் பாரம்பரியம்",
            desc: "திருநல்லூரின் பழமையான பாரம்பரியங்களில் ஒன்றை அனுபவிக்கவும். இங்கே காளைகள் வணங்கப்படுகின்றன, வீரம் சோதிக்கப்படுகிறது.",
            date: "தேதி: ஜனவரி 16 (மாட்டுப் பொங்கல்)",
            loc: "இடம்: திருநல்லூர், ஸ்ரீ முத்துமாரியம்மன் கோவில்.\nமாவட்டம்: புதுக்கோட்டை, அஞ்சல்: 621316"
        },
        countdown: {
            title: "பொங்கல்",
            subtitle: "திருவிழா துவக்கம்",
            days: "நாட்கள்"
        },
        booking: {
            title: "அதிகாரப்பூர்வ பதிவு",
            selectType: "பதிவு வகையைத் தேர்ந்தெடுக்கவும்",
            bullOwner: "காளை பதிவு",
            bullTamer: "மாடுபிடி வீரர் பதிவு",
            step1: "தனிப்பட்ட விவரங்கள்",
            step2: "கூடுதல் விவரங்கள்",
            step3: "ஆவணங்கள்",
            step4: "சரிபார்ப்பு & கட்டணம்",
            next: "அடுத்து",
            back: "பின்செல்",
            payBtn: "கட்டணம் செலுத்தவும்",
            processing: "செயலாக்குகிறது...",
            success: "பதிவு வெற்றி பெற்றது!",
            fields: {
                name: "முழு பெயர்",
                phone: "கைபேசி எண்",
                email: "மின்னஞ்சல்",
                aadhar: "ஆதார் எண்",
                district: "மாவட்டம்",
                village: "வருவாய் கிராமம்",
                address: "முழு முகவரி",
                bullName: "காளை பெயர்",
                bullAge: "காளை வயது",
                breed: "இனம்",
                height: "உயரம் (cm)",
                marks: "அடையாள குறிகள்",
                tamerAge: "வயது",
                weight: "எடை (kg)",
                bloodGroup: "இரத்த வகை",
                photo: "புகைப்படம்",
                aadharCard: "ஆதார் அட்டை",
                medicalCert: "மருத்துவ தகுதிச் சான்றிதழ்",
                vaccineCert: "தடுப்பூசி சான்றிதழ்",
                place: "ஊர்",
                bloodShort: "இரத்தம்",
                bullShort: "காளை",
                nameShort: "பெயர்",
                breedShort: "இனம்",
                weightShort: "எடை",
                aadharBull: "காளை புகைப்படத்துடன் ஆதார்",
                veterinary: "கால்நடை மருத்துவ சான்றிதழ்",
                fitness: "உடற்தகுதி சான்றிதழ்",
                animalWelfare: "விலங்குகள் நல வாரியம்",
                doorNo: "கதவு எண் / பகுதி / தெரு",
                taluk: "வட்டம்",
                pincode: "பின்கோடு",
                assistName: "உதவியாளர் பெயர்",
                assistMobile: "உதவியாளர் கைபேசி எண்",
                bullColor: "காளையின் நிறம்",
                bullDentition: "காளையின் பல்வரிசைகள்",
                bullNative: "காளை பூர்வீகமா?",
                hornLength: "காளை கொம்பின் நீளம் (cm)",
                icd: "கொம்புகளுக்கு இடையே உள்ள இடைவெளி (cm)",
                vetName: "கால்நடை மருந்தகத்தின் பெயர்",
                medicalCertNo: "காளையின் மருத்துவச் சான்றிதழ் எண்",
                vaccineFMD: "தடுப்பூசி விவரங்கள் (FMD)",
                ownerAadharFile: "ஆதார் பதிவேற்றம் (PDF மட்டும்)",
                bullMedicalFile: "மருத்துவச் சான்றிதழ் (PDF மட்டும்)",
                bullPhotoFile: "காளையின் படம், உரிமையாளர் & உதவியாளருடன் (JPG மட்டும்)",
                native: "பூர்வீகம்",
                cross: "கலப்பு",
                yes: "ஆம்",
                no: "இல்லை",
                pledge: "உரிமையாளர் உறுதிமொழி படிவம்",
                pledgeText: "மேலே குறிப்பிட்டுள்ள எனது ஜல்லிக்கட்டு காளை யினை அரசின் ஜல்லிக்கட்டு விதிகளுக்கு உட்பட்டு ஜல்லிக்கட்டில் பங்கேற்க செய்வேன் எனவும் எனது காளைக்கு ஊக்கமருந்து கொடுக்கவோ, துன்புறுத்தவோ மாட்டேன் எனவும் உறுதியளிக்கிறேன்.",
                // Tamer Specific
                tamerFormTitle: "ஜல்லிக்கட்டு காளையை அடக்குபவர் பதிவு படிவம்",
                hostingDistrict: "நடத்தும் மாவட்டத்தை தேர்ந்தெடுக்கவும்",
                jallikattuLocation: "ஜல்லிக்கட்டு இடம்",
                submittingLocation: "சமர்ப்பிக்கும் இடம்",
                emergencyName: "அவசரத் தொடர்பு நபரின் பெயர்",
                emergencyMobile: "அவசரத் தொடர்பு நபர் கைபேசி எண்",
                declarationTitle: "உறுதிமொழி",
                declarationRule1: "1. சமீபத்திய காயம்/அறுவை சிகிச்சை/அறுவை சிகிச்சை தழும்புகள் இருக்கக்கூடாது",
                declarationRule2: "2. பரிசோதனையில் உயர் இரத்த அழுத்த நோயாளிகள் அனுமதிக்கப்பட மாட்டார்கள்",
                declarationRule3: "3. ஜல்லிக்கட்டு அன்று மது அருந்தியுள்ளாரா என பரிசோதிக்கப்படும். மது அருந்தியிருப்பது கண்டறியப்பட்டால், விண்ணப்பதாரர் தகுதி நீக்கம் செய்யப்படுவார்"
            }
        }
    }
};
